# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
    ]
