# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('blog', '0004_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
